services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./payment_service/logs:/app/www/payment_service/logs
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - payment_service

  postgres:
    image: postgres:18-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  payment_service:
    build: .
    image: payment_service
    container_name: payment_service
    restart: always
    command: sh -c "python manage.py migrate && gunicorn -c gunicorn.py payment_service.wsgi"
    env_file:
      - .env
    volumes:
      - ./payment_service:/app/www/payment_service
    ports:
        - "8000:8000"
    depends_on:
      - postgres

  certbot:
  image: certbot/certbot
  volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
  command: certonly --webroot --webroot-path=/var/www/certbot --email ${ADMIN_EMAIL} --agree-tos --no-eff-email -d kirillblog.ru -d www.kirillblog.ru --non-interactive --keep-until-expiring
  depends_on:
    - nginx

volumes:
  postgres-data: