# Generated by Django 6.0 on 2025-12-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
    ]
